name: Gihub Pages
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./microbitMore
      - run: sh ./microbitMore/install.sh
      - run: npm run build
      - run: cp ./microbitMore/site/index.html ./build/index.html
      - run: cp ./microbitMore/site/favicon.ico ./build/static/favicon.ico
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build